version: '3.8'
name: ${APP_NAME} # name of the project; change to your project name
services:
  air:
    container_name: ${APP_NAME}-air # change to auth once on testing or production
    image: docker.io/cosmtrek/air
    restart: always
    ports:
      - '${PORT}:8080'
    volumes:
      - $PWD:$PWD
      - gocache:/root/.cache/go-build # cache for go modules; remove if not using air
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: $PWD
    env_file:
      - .env
    environment:
      - GOCACHE=/root/.cache/go-build # cache for go modules; remove if not using air
volumes:
  gocache: