// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package schema

import (
	"time"
)

type User struct {
	ID         string    `json:"id"`
	Email      string    `json:"email"`
	Provider   string    `json:"provider"`
	ProviderID string    `json:"provider_id"`
	CreatedAt  time.Time `json:"created_at"`
}
