name: Go-test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      GOPRIVATE: github.com/parsel-email/*
      CGO_ENABLED: 1

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.x'

      - name: Test with the Go CLI
        run: go test ./...
